/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Capa_Presentacion;

import Capa_Negocio.clsProducto;
import Capa_Negocio.clsREPORTE;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Frame; // Importar Frame
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.swing.JRViewer;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel; // Para manejar el JTable
import javax.swing.SwingUtilities; // Para obtener el Frame padre
// Importamos JRRuntimeException para un manejo más específico de errores de reporte
import net.sf.jasperreports.engine.JRRuntimeException;

/**
 *
 * @author USER
 */
public class jdReporteProductosPorPresentación extends javax.swing.JDialog {

    /**
     * Creates new form jdReporteProductosPorPresentación
     */
    private final clsProducto objProducto = new clsProducto();
    private int codProductoSeleccionado = 0;
    
    public jdReporteProductosPorPresentación(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listarProductos();
    }
    
     private void listarProductos() {
        ResultSet rsProductos = null;
        DefaultTableModel modelo = new DefaultTableModel();
        // Solo necesitamos CÓDIGO y NOMBRE en esta vista
        modelo.addColumn("CÓDIGO");
        modelo.addColumn("NOMBRE"); 
        
        try {
            // Filtrar usa el texto del txtNombreProducto
            rsProductos = objProducto.filtrar(txtNombreProducto.getText(), 0, 99999);
            
            while(rsProductos.next()){
                modelo.addRow(new Object[]{
                    rsProductos.getInt("idproducto"),
                    rsProductos.getString("nombre")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al listar productos: " + e.getMessage());
        } finally {
             // Cerrar ResultSet y Conexión para liberar recursos
            if (rsProductos != null) {
                try {
                    // Cierra el ResultSet y la conexión asociada (ver clsJDBC)
                    rsProductos.getStatement().getConnection().close(); 
                } catch (SQLException ex) {
                    // Manejar error de cierre
                } catch (Exception e) {
                    // Manejo de error general al intentar cerrar
                }
            }
        }
        
        tblProductos.setModel(modelo);
        // Ocultar columna de código para el usuario (opcional, pero buena práctica)
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(0).setMaxWidth(0);
            tblProductos.getColumnModel().getColumn(0).setMinWidth(0);
            tblProductos.getColumnModel().getColumn(0).setPreferredWidth(0);
        }
    }
  
  
  private void seleccionarProducto(int cod) {
        try {
            // Guardar el código seleccionado
            codProductoSeleccionado = cod;
            
            // Obtener el nombre del producto para mostrarlo en el JTextField
            String nombre = objProducto.getNombreProducto(cod);
            txtNombreProducto.setText(nombre);
            
            // Opcional: Ocultar la tabla después de la selección
            // jScrollPane1.setVisible(false);
            
            JOptionPane.showMessageDialog(this, "Producto seleccionado: " + nombre);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al seleccionar producto: " + e.getMessage());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenu1 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        txtNombreProducto = new javax.swing.JTextField();
        btnBusqueda = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        vistaReporte = new javax.swing.JDesktopPane();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Buscar producto:");

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        txtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });
        txtNombreProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreProductoKeyReleased(evt);
            }
        });

        btnBusqueda.setText("BÚSQUEDA AVANZADA");
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });

        jButton2.setText("Ver reporte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vistaReporteLayout = new javax.swing.GroupLayout(vistaReporte);
        vistaReporte.setLayout(vistaReporteLayout);
        vistaReporteLayout.setHorizontalGroup(
            vistaReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        vistaReporteLayout.setVerticalGroup(
            vistaReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(133, 133, 133)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vistaReporte))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBusqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(353, Short.MAX_VALUE))
            .addComponent(vistaReporte)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        int filaSeleccionada = tblProductos.getSelectedRow();
        if (filaSeleccionada != -1) {
            // El código está en la columna 0 (que se ocultó)
            int cod = Integer.parseInt(String.valueOf(tblProductos.getValueAt(filaSeleccionada, 0)));
            seleccionarProducto(cod);
        }
    }//GEN-LAST:event_tblProductosMouseClicked

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void txtNombreProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProductoKeyReleased
        listarProductos();
        // Al empezar a escribir, reiniciamos la selección (asumiendo que busca otro)
        codProductoSeleccionado = 0;
    }//GEN-LAST:event_txtNombreProductoKeyReleased

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        // Se mantiene la lógica de búsqueda avanzada si la clase jdBusquedaAvanzada
        // está disponible y devuelve el código del producto.
        jdBusquedaAvanzada objConsulta =
        new jdBusquedaAvanzada((Frame) SwingUtilities.getWindowAncestor(this), true);

        objConsulta.setBuscando(true);
        objConsulta.setLocationRelativeTo(this);
        objConsulta.setVisible(true);

        int cod = objConsulta.getCod(); // Asumiendo que getCod() devuelve el ID del producto

        if (cod > 0) {
            // En este reporte solo queremos el código, no la cantidad/descuento
            seleccionarProducto(cod);
        }
    }//GEN-LAST:event_btnBusquedaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // --- 1. CAPTURAR VALORES ---
           
            int productoID = codProductoSeleccionado;

            // --- 2. PREPARAR LOS PARÁMETROS ---
            Map<String, Object> parametros = new java.util.HashMap<>();
     
            parametros.put("p_id_producto", productoID);

            // --- 3. GENERAR EL REPORTE ---
            JRViewer objReporte = new clsREPORTE().reporteInterno("rp_productoPorPresentacion.jasper", parametros);

            // --- 4. VERIFICAR RESULTADOS Y MOSTRAR ---

            // El JRViewer creado es el reporte mismo. No tiene un método getReportViewer().
            // En este punto, si el reporte no tiene datos, JasperReports *suele* lanzar una JRRuntimeException.
            // Si no lanza una excepción, verificamos si es null.

            if (objReporte == null) {
                // Esto solo se activaría si clsReporte.reporteInterno devuelve null explícitamente
                throw new Exception("El objeto de reporte es nulo. Verifique la conexión o el archivo .jasper.");
            }

            // NOTA: Para verificar el número de páginas, la forma correcta puede ser
            // objReporte.getViewer().getPages().size() si tu versión de Jasper es antigua,
            // o depender de la excepción JRRuntimeException que ya estamos capturando.
            // Vamos a depender de la captura de excepción para el "No Data", que es el patrón más común.

            // Si no se lanzó excepción, asumimos que tiene contenido y lo mostramos
            Container contenedor = this.vistaReporte;
            contenedor.setLayout(new BorderLayout());
            contenedor.removeAll();

            contenedor.add(objReporte);
            contenedor.revalidate();
            contenedor.repaint();
            objReporte.setVisible(true);

            this.vistaReporte.setVisible(true);

        } catch (net.sf.jasperreports.engine.JRRuntimeException e) {
            // Esta excepción se lanza típicamente cuando el data source está vacío
            // y el reporte no tiene un manejo explícito de "No Data".

            try {
                // Intentar obtener el nombre del producto de forma segura aquí
                int productoID = codProductoSeleccionado;
                String nombreProducto = (productoID > 0) ? objProducto.getNombreProducto(productoID) : null;

                String mensaje = (productoID == 0) ?
                "No hay lotes próximos a vencer en los días seleccionados." :
                "No se encontraron lotes próximos a vencer para el producto '" + nombreProducto + "' en los días seleccionados.";

                JOptionPane.showMessageDialog(this, mensaje, "Sin Resultados", JOptionPane.INFORMATION_MESSAGE);
                this.vistaReporte.setVisible(false);

            } catch (Exception exInterno) {
                // Manejar error si falla la obtención del nombre del producto (secundario)
                JOptionPane.showMessageDialog(this, "No se encontraron lotes. (Error interno al obtener nombre: " + exInterno.getMessage() + ")",
                    "Sin Resultados", JOptionPane.INFORMATION_MESSAGE);
                this.vistaReporte.setVisible(false);
            }

        } catch (Exception e) {
            // Para cualquier otro error inesperado (conexión, consulta SQL fallida, etc.)
            JOptionPane.showMessageDialog(this, "ERROR grave en Reporte: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
            this.vistaReporte.setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBusqueda;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JDesktopPane vistaReporte;
    // End of variables declaration//GEN-END:variables
}
