/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Capa_Presentacion;
import Capa_Datos.clsJDBC;
import Capa_Negocio.clsCategoria;
import Capa_Negocio.clsLaboratorio;
import Capa_Negocio.clsMarca;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;
/**
 *
 * @author USER
 */
public class jdReporteStockMin extends javax.swing.JDialog {

    /**
     * Creates new form jdReporteStockMin
     */
    
    public class ItemCombo {
        private int id;
        private String descripcion;

        public ItemCombo(int id, String descripcion) {
            this.id = id;
            this.descripcion = descripcion;
        }

        public int getId() { return id; }

        @Override
        public String toString() { return descripcion; }
    }
    
    public jdReporteStockMin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarCombos();
    }
    
    private void cargarCombos() {
        try {
            // A. Cargar Laboratorios
            cboLaboratorio.removeAllItems();
            cboLaboratorio.addItem(new ItemCombo(0, "--- TODOS ---"));
            
            clsLaboratorio objLab = new clsLaboratorio();
            ResultSet rsLab = objLab.listarLaboratoriosActivos(); // Usamos tu método existente
            
            while (rsLab.next()) {
                // OJO: Asegúrate de usar los nombres de columna exactos de tu BD
                cboLaboratorio.addItem(new ItemCombo(
                    rsLab.getInt("idlaboratorio"), 
                    rsLab.getString("nombrelaboratorio")
                ));
            }



            // C. Cargar Categorias
            cboCategoria.removeAllItems();
            cboCategoria.addItem(new ItemCombo(0, "--- TODOS ---"));
            
            clsCategoria objCat = new clsCategoria();
            ResultSet rsCat = objCat.listarCategoriasActivas(); // Usamos tu método existente
            
            while (rsCat.next()) {
                cboCategoria.addItem(new ItemCombo(
                    rsCat.getInt("idcategoria"), 
                    rsCat.getString("nombrecategoria")
                ));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error cargando datos: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboLaboratorio = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cboCategoria = new javax.swing.JComboBox<>();
        btnVerReporte = new javax.swing.JButton();
        vistaReporte = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Laboratorio:");

        cboLaboratorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Categoria");

        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnVerReporte.setText("Ver reporte");
        btnVerReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vistaReporteLayout = new javax.swing.GroupLayout(vistaReporte);
        vistaReporte.setLayout(vistaReporteLayout);
        vistaReporteLayout.setHorizontalGroup(
            vistaReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );
        vistaReporteLayout.setVerticalGroup(
            vistaReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboLaboratorio, 0, 125, Short.MAX_VALUE)
                            .addComponent(cboCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVerReporte)
                        .addGap(75, 75, 75)))
                .addComponent(vistaReporte)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnVerReporte)
                .addContainerGap(231, Short.MAX_VALUE))
            .addComponent(vistaReporte)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReporteActionPerformed
        clsJDBC jdbc = new clsJDBC(); // Instanciamos TU clase de conexión
        Connection con = null;

        try {
            // Usamos tu método conectar()
            con = jdbc.conectar(); 
            
            Map<String, Object> parametros = new HashMap<>();
            
            // Lógica Laboratorio
            if (cboLaboratorio.getSelectedIndex() == 0) {
                parametros.put("p_idlaboratorio", null);
            } else {
                ItemCombo item = (ItemCombo) cboLaboratorio.getSelectedItem();
                parametros.put("p_idlaboratorio", item.getId());
            }
            
 

            // Lógica Categoria
            if (cboCategoria.getSelectedIndex() == 0) {
                parametros.put("p_idcategoria", null);
            } else {
                ItemCombo item = (ItemCombo) cboCategoria.getSelectedItem();
                parametros.put("p_idcategoria", item.getId());
            }
            
            // Ruta del reporte
            String rutaReporte = "src/Reportes/rp_StockMin.jasper"; 
            
            // Llenamos el reporte pasando la conexión 'con' que obtuvimos de clsJDBC
            JasperPrint print = JasperFillManager.fillReport(rutaReporte, parametros, con);
            
            // Mostrar en el JDesktopPane
            vistaReporte.removeAll();
            JInternalFrame frame = new JInternalFrame("Vista Previa");
            frame.getContentPane().add(new JRViewer(print));
            frame.pack();
            frame.setSize(vistaReporte.getSize());
            frame.setVisible(true);
            frame.setClosable(true);
            frame.setMaximizable(true);
            try { frame.setMaximum(true); } catch(Exception e) {}
            
            vistaReporte.add(frame);
            vistaReporte.repaint();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al generar reporte: " + e.getMessage());
        }
    }//GEN-LAST:event_btnVerReporteActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerReporte;
    private javax.swing.JComboBox<Object> cboCategoria;
    private javax.swing.JComboBox<Object> cboLaboratorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JDesktopPane vistaReporte;
    // End of variables declaration//GEN-END:variables
}
