/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Capa_Presentacion;

import Capa_Negocio.clsProducto;
import Capa_Negocio.clsREPORTE;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Frame; // Importar Frame
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.swing.JRViewer;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel; // Para manejar el JTable
import javax.swing.SwingUtilities; // Para obtener el Frame padre
// Importamos JRRuntimeException para un manejo más específico de errores de reporte
import net.sf.jasperreports.engine.JRRuntimeException;

/**
 *
 * @author USER
 */
public class jsLotesAVencer extends javax.swing.JDialog {
 private final clsProducto objProducto = new clsProducto();
    /**
     * Creates new form jsLotesAVencer
     */
    // Variable para almacenar el código del producto seleccionado
    private int codProductoSeleccionado = 0;
    
    public jsLotesAVencer(java.awt.Frame parent, boolean modal) {
       super(parent, modal);
        initComponents();
        this.vistaReporte.setVisible(false);
        txtUsuario.setText(FrmLogin.nomUser);
        txtUsuario.setEditable(false);
        this.setTitle("Reporte de lotes a vencer");
        
        // Configuración inicial del JComboBox1 (DÍAS)
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
            "30 días", "60 días", "90 días", "180 días" 
        }));
        jComboBox1.setSelectedIndex(2); // 90 días por defecto
        
        // Inicializar la tabla de productos
        listarProductos();
    }
    
  private void listarProductos() {
        ResultSet rsProductos = null;
        DefaultTableModel modelo = new DefaultTableModel();
        // Solo necesitamos CÓDIGO y NOMBRE en esta vista
        modelo.addColumn("CÓDIGO");
        modelo.addColumn("NOMBRE"); 
        
        try {
            // Filtrar usa el texto del txtNombreProducto
            rsProductos = objProducto.filtrar(txtNombreProducto.getText(), 0, 99999);
            
            while(rsProductos.next()){
                modelo.addRow(new Object[]{
                    rsProductos.getInt("idproducto"),
                    rsProductos.getString("nombre")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al listar productos: " + e.getMessage());
        } finally {
             // Cerrar ResultSet y Conexión para liberar recursos
            if (rsProductos != null) {
                try {
                    // Cierra el ResultSet y la conexión asociada (ver clsJDBC)
                    rsProductos.getStatement().getConnection().close(); 
                } catch (SQLException ex) {
                    // Manejar error de cierre
                } catch (Exception e) {
                    // Manejo de error general al intentar cerrar
                }
            }
        }
        
        tblProductos.setModel(modelo);
        // Ocultar columna de código para el usuario (opcional, pero buena práctica)
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(0).setMaxWidth(0);
            tblProductos.getColumnModel().getColumn(0).setMinWidth(0);
            tblProductos.getColumnModel().getColumn(0).setPreferredWidth(0);
        }
    }
  
  
  private void seleccionarProducto(int cod) {
        try {
            // Guardar el código seleccionado
            codProductoSeleccionado = cod;
            
            // Obtener el nombre del producto para mostrarlo en el JTextField
            String nombre = objProducto.getNombreProducto(cod);
            txtNombreProducto.setText(nombre);
            
            // Opcional: Ocultar la tabla después de la selección
            // jScrollPane1.setVisible(false);
            
            JOptionPane.showMessageDialog(this, "Producto seleccionado: " + nombre);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al seleccionar producto: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel22 = new javax.swing.JLabel();
        vistaReporte = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnBusqueda = new javax.swing.JToggleButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Venta");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout vistaReporteLayout = new javax.swing.GroupLayout(vistaReporte);
        vistaReporte.setLayout(vistaReporteLayout);
        vistaReporteLayout.setHorizontalGroup(
            vistaReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        vistaReporteLayout.setVerticalGroup(
            vistaReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(230, 243, 243));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Días Próx. a Vencer:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Buscar producto:");

        txtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });
        txtNombreProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreProductoKeyReleased(evt);
            }
        });

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        btnBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/buscar1.png"))); // NOI18N
        btnBusqueda.setText("BÚSQUEDA AVANZADA");
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btnBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBusqueda)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(153, 204, 255));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo.png"))); // NOI18N
        jLabel19.setText("jLabel1");

        jLabel20.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Farmacia Salud Vida");

        jLabel21.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Usuario:");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21))
                    .addComponent(jLabel19)))
        );

        jPanel5.setBackground(new java.awt.Color(51, 102, 255));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Reporte de lotes vencer");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Visualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(vistaReporte)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vistaReporte))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   try {
        // --- 1. CAPTURAR VALORES ---
        String seleccion = (String) jComboBox1.getSelectedItem();
        int rangoDias = Integer.parseInt(seleccion.split(" ")[0]);  
        int productoID = codProductoSeleccionado;

        // --- 2. PREPARAR LOS PARÁMETROS ---
        Map<String, Object> parametros = new java.util.HashMap<>();
        parametros.put("RANGO_DIAS", rangoDias);  
        parametros.put("P_PRODUCTO_ID", productoID);  

        // --- 3. GENERAR EL REPORTE ---
        JRViewer objReporte = new clsREPORTE().reporteInterno("rp_lotesAVencer.jasper", parametros);

        // --- 4. VERIFICAR RESULTADOS Y MOSTRAR ---
        
        // El JRViewer creado es el reporte mismo. No tiene un método getReportViewer().
        // En este punto, si el reporte no tiene datos, JasperReports *suele* lanzar una JRRuntimeException.
        // Si no lanza una excepción, verificamos si es null.

        if (objReporte == null) {
            // Esto solo se activaría si clsReporte.reporteInterno devuelve null explícitamente
            throw new Exception("El objeto de reporte es nulo. Verifique la conexión o el archivo .jasper.");
        }
        
        // NOTA: Para verificar el número de páginas, la forma correcta puede ser
        // objReporte.getViewer().getPages().size() si tu versión de Jasper es antigua,
        // o depender de la excepción JRRuntimeException que ya estamos capturando.
        // Vamos a depender de la captura de excepción para el "No Data", que es el patrón más común.
        
        // Si no se lanzó excepción, asumimos que tiene contenido y lo mostramos
        Container contenedor = this.vistaReporte;
        contenedor.setLayout(new BorderLayout());
        contenedor.removeAll();

        contenedor.add(objReporte);
        contenedor.revalidate();
        contenedor.repaint();
        objReporte.setVisible(true);

        this.vistaReporte.setVisible(true);

    } catch (net.sf.jasperreports.engine.JRRuntimeException e) {
        // Esta excepción se lanza típicamente cuando el data source está vacío 
        // y el reporte no tiene un manejo explícito de "No Data".
        
        try {
            // Intentar obtener el nombre del producto de forma segura aquí
            int productoID = codProductoSeleccionado;
            String nombreProducto = (productoID > 0) ? objProducto.getNombreProducto(productoID) : null;
            
            String mensaje = (productoID == 0) ? 
                             "No hay lotes próximos a vencer en los días seleccionados." :
                             "No se encontraron lotes próximos a vencer para el producto '" + nombreProducto + "' en los días seleccionados.";
                             
            JOptionPane.showMessageDialog(this, mensaje, "Sin Resultados", JOptionPane.INFORMATION_MESSAGE);
            this.vistaReporte.setVisible(false);
            
        } catch (Exception exInterno) {
            // Manejar error si falla la obtención del nombre del producto (secundario)
            JOptionPane.showMessageDialog(this, "No se encontraron lotes. (Error interno al obtener nombre: " + exInterno.getMessage() + ")", 
                                         "Sin Resultados", JOptionPane.INFORMATION_MESSAGE);
            this.vistaReporte.setVisible(false);
        }

    } catch (Exception e) {
        // Para cualquier otro error inesperado (conexión, consulta SQL fallida, etc.)
        JOptionPane.showMessageDialog(this, "ERROR grave en Reporte: " + e.getMessage(), 
                                     "Error", JOptionPane.ERROR_MESSAGE);
        this.vistaReporte.setVisible(false);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void txtNombreProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProductoKeyReleased
      listarProductos();
        // Al empezar a escribir, reiniciamos la selección (asumiendo que busca otro)
        codProductoSeleccionado = 0;
    }//GEN-LAST:event_txtNombreProductoKeyReleased

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
       int filaSeleccionada = tblProductos.getSelectedRow();
        if (filaSeleccionada != -1) {
            // El código está en la columna 0 (que se ocultó)
            int cod = Integer.parseInt(String.valueOf(tblProductos.getValueAt(filaSeleccionada, 0)));
            seleccionarProducto(cod);
        }
    }//GEN-LAST:event_tblProductosMouseClicked

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        // Se mantiene la lógica de búsqueda avanzada si la clase jdBusquedaAvanzada
        // está disponible y devuelve el código del producto.
        jdBusqAvanzada objConsulta =
        new jdBusqAvanzada((Frame) SwingUtilities.getWindowAncestor(this), true);

        objConsulta.setBuscando(true);
        objConsulta.setLocationRelativeTo(this);
        objConsulta.setVisible(true);

        int cod = objConsulta.getCod(); // Asumiendo que getCod() devuelve el ID del producto

        if (cod > 0) {
            // En este reporte solo queremos el código, no la cantidad/descuento
            seleccionarProducto(cod); 
        }
    }//GEN-LAST:event_btnBusquedaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBusqueda;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JDesktopPane vistaReporte;
    // End of variables declaration//GEN-END:variables
}
